version: "3.3"
services:
  airsonic:
    image: gavin0228/ktvcreator:1.0
    container_name: ktvcreator
    volumes:
      - D:\AppData\ktvcreator:/usr/src/app/working
    ports:
      - 8080:80
    environment:
      - NUMBER_OF_WORKERS=1
      - WORKER_TIMEOUT=120
    restart: always